# Generated by Django 6.0.5 on 2026-06-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('author', models.CharField(max_length=255, verbose_name='autor')),
                ('editorial', models.CharField(blank=True, max_length=255, verbose_name='editorial')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='año')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='precio (COP)')),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('como_nuevo', 'Como nuevo'), ('bueno', 'Bueno'), ('aceptable', 'Aceptable')], default='bueno', max_length=20, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='portada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
