# Generated by Django 6.0.5 on 2026-06-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/gallery/', verbose_name='imagen')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='leyenda')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.book', verbose_name='libro')),
            ],
            options={
                'verbose_name': 'imagen del libro',
                'verbose_name_plural': 'imágenes del libro',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
