# Generated by Django 6.0.5 on 2026-06-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_bookimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono de contacto')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones adicionales')),
                ('is_saved', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número de pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20)),
                ('payment_method', models.CharField(choices=[('pse', 'PSE'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('card', 'Tarjeta crédito/débito')], max_length=20)),
                ('shipping_line1', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_department', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('shipping_phone', models.CharField(max_length=30)),
                ('shipping_instructions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
            },
        ),
    ]
